# Notebook in the "Stellarphot setup" section of the launcher

- title: 1 - Saveable settings
  description: Settings for camera, observatory and passbands
  source: ../stellarphot/01-initial-settings.ipynb
  icon: ../stellarphot/stellarphot-logo.svg
  cwd: not_used
  type: notebook
  catalog: Stellarphot setup

# Notebook in the "Stellarphot photometry" section of the launcher

- title: 2 - Seeing profile and comparison stars
  description: Choose aperture settings and stars to perform photometry on
  source: ../stellarphot/02-seeing-and-comparison.ipynb
  icon: ../stellarphot/stellarphot-logo.svg
  cwd: not_used
  type: notebook
  catalog: Stellarphot photometry

- title: 3 - Review settings
  description: Choose comparison stars
  source: ../stellarphot/03-final-review-of-settings.ipynb
  icon: ../stellarphot/stellarphot-logo.svg
  cwd: not_used
  type: notebook
  catalog: Stellarphot photometry

- title: 4 - Launch photometry
  description: Perform photometry on images
  source: ../stellarphot/04-launch-photometry.ipynb
  icon: ../stellarphot/stellarphot-logo.svg
  cwd: not_used
  type: notebook
  catalog: Stellarphot photometry

# Notebook in the "Stellarphot analysis and tools" section of the launcher

- title: Generate TESS target list
  description: Retrieve TESS target list and TIC information
  source: ../stellarphot/tess-target-source-list-generator.ipynb
  icon: ../stellarphot/stellarphot-logo.svg
  cwd: not_used
  type: notebook
  catalog: Stellarphot analysis and tools

- title: Calculate relative flux
  description: Add a relative flux column to the photometry table
  source: ../stellarphot/relative-flux-calculation.ipynb
  icon: ../stellarphot/stellarphot-logo.svg
  cwd: not_used
  type: notebook
  catalog: Stellarphot analysis and tools

- title: Calibrate magnitudes
  description: Calibrate magnitudes to APASS DR9
  source: ../stellarphot/transform-to-appas-dr9.ipynb
  icon: ../stellarphot/stellarphot-logo.svg
  cwd: not_used
  type: notebook
  catalog: Stellarphot analysis and tools

- title: Initial exoplanet model
  description: Do an initial fit to a transit
  source: ../stellarphot/tess-initial-model-fit.ipynb
  icon: ../stellarphot/stellarphot-logo.svg
  cwd: not_used
  type: notebook
  catalog: Stellarphot analysis and tools

- title: Second exoplanet model fit
  description: Second transit model fit
  source: ../stellarphot/tess-second-model-fit.ipynb
  icon: ../stellarphot/stellarphot-logo.svg
  cwd: not_used
  type: notebook
  catalog: Stellarphot analysis and tools

- title: Exoplanet model fit with EXOTIC
  description: The final exoplanet fit
  source: ../stellarphot/tess-EXOTIC-fit.ipynb
  icon: ../stellarphot/stellarphot-logo.svg
  cwd: not_used
  type: notebook
  catalog: Stellarphot analysis and tools
