import numpy as np
import pytest
from astropy.table import Table
from astropy.utils.data import get_pkg_data_filename

from stellarphot.transit_fitting import TransitModelFit

pytest.importorskip("pytransit")
pytest.importorskip("lmfit")

REFERENCE_FILE = get_pkg_data_filename("data/batman_reference_lightcurves.ecsv")

DEFAULT_TESTING_PARAMS = dict(
    t0=2,
    period=5,
    duration=0.1,
    depth=10,
    inclination=90,
    airmass_trend=0.005,
    width_trend=0.01,
    spp_trend=0.002,
)


def _create_data_from_model_with_trends(transit_model, noise_dev=0.01, seed=432132):
    # Given a fully set up transit model, create some fake data with a touch of
    # noise. The ground-truth light curve (transit plus any trends that are set)
    # is generated by the pytransit-backed model itself.
    data = transit_model.model_light_curve()

    if noise_dev > 0:
        # Make some noise
        generator = np.random.default_rng(seed)
        noise = generator.normal(scale=noise_dev, size=len(data))

        data += noise

    return data


def test_pytransit_matches_batman_reference():
    # pytransit replaced batman-package as the transit light-curve engine. This
    # checks that pytransit reproduces a set of reference light curves that were
    # generated once with batman (the fixture header records the parameters).
    # Running this test only requires the committed fixture and pytransit --
    # batman itself is not a test dependency.
    from pytransit import RoadRunnerModel

    reference = Table.read(REFERENCE_FILE)
    cases = reference.meta["cases"]

    tm = RoadRunnerModel("quadratic")

    # Observed agreement between pytransit and batman is ~1e-5 or better across
    # these cases; 1e-4 leaves comfortable margin for platform differences.
    tolerance = 1e-4

    for case in cases:
        rows = reference[reference["case"] == case["name"]]
        times = np.asarray(rows["time"], dtype=float)
        tm.set_data(times)
        flux = tm.evaluate(
            k=case["rp"],
            ldc=[case["u1"], case["u2"]],
            t0=case["t0"],
            p=case["period"],
            a=case["a"],
            i=np.radians(case["inc"]),
        )
        np.testing.assert_allclose(
            flux,
            np.asarray(rows["flux"], dtype=float),
            atol=tolerance,
            err_msg=(
                f"pytransit disagrees with the batman reference for case {case['name']}"
            ),
        )


def test_transit_model_fit_requires_pytransit(monkeypatch):
    # If pytransit is not installed, constructing a TransitModelFit should fail
    # with a clear, actionable error rather than a cryptic one.
    from stellarphot.transit_fitting import core

    monkeypatch.setattr(core, "RoadRunnerModel", None)
    with pytest.raises(ImportError, match="install pytransit"):
        TransitModelFit()


def test_transit_model_fit_requires_lmfit(monkeypatch):
    # If lmfit is not installed, constructing a TransitModelFit should fail
    # with a clear, actionable error rather than a cryptic one. lmfit is
    # guarded with the same optional-import pattern as pytransit.
    from stellarphot.transit_fitting import core

    monkeypatch.setattr(core, "lmfit", None)
    with pytest.raises(ImportError, match="lmfit"):
        TransitModelFit()


def test_model_light_curve_at_times_restores_original_times():
    # Evaluating the model at a different set of times should not disturb the
    # model's configured times (the pytransit model is temporarily repointed
    # and then restored).
    tmod = _make_transit_model_with_data(
        noise_dev=0, with_airmass=False, with_width=False, with_spp=False
    )

    baseline = tmod.model_light_curve()

    at_times = np.linspace(tmod.times[0], tmod.times[-1], len(tmod.times))
    shifted = tmod.model_light_curve(at_times=at_times)
    assert len(shifted) == len(at_times)

    # The original times are restored, so a subsequent call matches the baseline.
    np.testing.assert_allclose(tmod.model_light_curve(), baseline)


def test_model_light_curve_at_times_length_mismatch_raises():
    # at_times reuses the stored airmass/width/spp covariates, so it must match
    # the model's time length. A mismatched length is a clear error rather than
    # a numpy broadcasting crash, and it must be raised *before* the pytransit
    # model is repointed so the instance is not left corrupted.
    tmod = _make_transit_model_with_data(
        noise_dev=0, with_airmass=True, with_width=True, with_spp=True
    )

    baseline = tmod.model_light_curve()

    bad_times = np.linspace(tmod.times[0], tmod.times[-1], len(tmod.times) + 5)
    with pytest.raises(ValueError, match="same length"):
        tmod.model_light_curve(at_times=bad_times)

    # The failed call must not corrupt the model: a normal call still works and
    # returns the same result as before.
    np.testing.assert_allclose(tmod.model_light_curve(), baseline)


def test_model_light_curve_requires_times():
    # model_light_curve() is public API; if called before times are set it
    # should fail fast with a clear ValueError (mirroring fit()) rather than a
    # cryptic error from evaluating the pytransit model without times. Unlike
    # the old interface, `mod.params` always exists from construction, so
    # there is no separate "setup_model first" failure mode to check here.
    tmod = TransitModelFit()

    with pytest.raises(ValueError, match="times must be set"):
        tmod.model_light_curve()


def test_transit_fit_value_length_check():
    # Check that setting inconsistent lengths raises an error
    tmod = TransitModelFit()

    # Should work, all others are None
    tmod.times = np.array(list(range(5)))

    # Should work, new length is 5
    tmod.airmass = list(range(5))

    # Each of these should raise an error, has different length
    with pytest.raises(ValueError) as e:
        tmod.spp = list(range(3))
    assert "Length of spp not consistent" in str(e.value)

    with pytest.raises(ValueError) as e:
        tmod.width = list(range(3))
    assert "Length of width not consistent" in str(e.value)

    with pytest.raises(ValueError) as e:
        tmod.times = list(range(3))
    assert "Length of times not consistent" in str(e.value)

    with pytest.raises(ValueError) as e:
        tmod.airmass = list(range(3))
    assert "Length of airmass not consistent" in str(e.value)

    with pytest.raises(ValueError) as e:
        tmod.data = list(range(3))
    assert "Length of data not consistent" in str(e.value)


@pytest.mark.parametrize("detrend_by", ["airmass", "spp", "width"])
def test_setting_unsetting_parameters_updates_detrend(detrend_by):
    tmod = TransitModelFit()

    dummy_values = np.array(list(range(5)))
    # Should work, all others are None
    tmod.times = dummy_values

    setattr(tmod, detrend_by, dummy_values)
    assert detrend_by in tmod._detrend_parameters

    setattr(tmod, detrend_by, None)
    assert detrend_by not in tmod._detrend_parameters


def test_transit_fit_setting_independent_vars():
    tmod = TransitModelFit()

    values = np.array(list(range(5)))

    for attr in ["times", "airmass", "width", "spp"]:
        setattr(tmod, attr, values)
        assert (getattr(tmod, attr) == values).all()


def test_transit_fit_setting_independent_vars_to_none():
    """
    Setting to None should always work.
    """
    tmod = TransitModelFit()

    values = np.array(list(range(5)))

    # First set values to something that is not None
    for attr in ["times", "airmass", "width", "spp", "data"]:
        setattr(tmod, attr, values)

    # Now set to None and check value
    for attr in ["times", "airmass", "width", "spp", "data"]:
        setattr(tmod, attr, None)
        assert getattr(tmod, attr) is None


def test_transit_create_model():
    # Creating a model should not give us an error and should lead
    # to expected values of parameters.
    tmod = TransitModelFit()

    tmod.setup_model(**DEFAULT_TESTING_PARAMS)

    duration = DEFAULT_TESTING_PARAMS["duration"]
    period = DEFAULT_TESTING_PARAMS["period"]

    expected_a = 1 / np.sin(duration * np.pi / period)
    assert tmod.params["t0"].value == DEFAULT_TESTING_PARAMS["t0"]
    assert tmod.params["period"].value == DEFAULT_TESTING_PARAMS["period"]
    assert tmod.params["rp"].value == np.sqrt(DEFAULT_TESTING_PARAMS["depth"] / 1000)
    assert np.abs(tmod.params["a"].value - expected_a) < 1e-7
    assert tmod.params["airmass_trend"].value == DEFAULT_TESTING_PARAMS["airmass_trend"]
    assert tmod.params["width_trend"].value == DEFAULT_TESTING_PARAMS["width_trend"]
    assert tmod.params["spp_trend"].value == DEFAULT_TESTING_PARAMS["spp_trend"]

    # Bounds are set up regardless of the values passed to setup_model.
    assert tmod.params["a"].min == 1.0
    assert tmod.params["inclination"].min == 50
    assert tmod.params["inclination"].max == 90
    assert tmod.params["rp"].min == 0.01
    assert tmod.params["rp"].max == 0.5

    # Trend fitting is opt-in: the trend parameters default to not varying,
    # even though this call seeded them with nonzero values.
    assert tmod.params["airmass_trend"].vary is False
    assert tmod.params["width_trend"].vary is False
    assert tmod.params["spp_trend"].vary is False

    # period is held fixed by default; t0 varies by default.
    assert tmod.params["period"].vary is False
    assert tmod.params["t0"].vary is True


def _make_transit_model_with_data(
    noise_dev=1e-1, with_airmass=False, with_width=False, with_spp=False
):
    tmod = TransitModelFit()

    tmod.setup_model(**DEFAULT_TESTING_PARAMS)

    t0 = DEFAULT_TESTING_PARAMS["t0"]
    duration = DEFAULT_TESTING_PARAMS["duration"]

    # Last factor ensures some out of transit data
    start = t0 - duration / 2 * 1.3
    end = t0 + duration / 2 * 1.3

    times = np.linspace(start, end, num=100)
    tmod.times = times

    # Make an airmass that starts at 1.4 and decreases to 1.0
    # over the duration and is parabolic centered on the final time.
    airmass = 0.4 / (times[0] - times[-1]) ** 2 * (times - times[-1]) ** 2 + 1.0

    tmod.airmass = airmass if with_airmass else None
    if with_airmass:
        # Trend fitting is opt-in: enable fitting for every covariate this
        # helper actually supplies.
        tmod.params["airmass_trend"].vary = True

    # Make a width that increases linearly with time. Never happen IRL, but
    # that is ok. Let's start at 5 pixels and increase to 9.
    width = 4 * (times - times[0]) / (times[-1] - times[0]) + 5

    tmod.width = width if with_width else None
    if with_width:
        tmod.params["width_trend"].vary = True

    # sky_per_pixel...let's make that sinusoidal. Not realistic but should be
    # easy for the fitter to pick out this trend.
    spp = 30 + 5 * np.sin(4 * np.pi * times / (times[-1] - times[0]))

    tmod.spp = spp if with_spp else None
    if with_spp:
        tmod.params["spp_trend"].vary = True

    data = _create_data_from_model_with_trends(tmod, noise_dev=noise_dev)

    tmod.data = data

    return tmod


def test_transit_fit_all_parameters():
    tmod = _make_transit_model_with_data(
        noise_dev=1e-5, with_airmass=True, with_width=True, with_spp=True
    )

    duration = DEFAULT_TESTING_PARAMS["duration"]
    period = DEFAULT_TESTING_PARAMS["period"]

    expected_a = 1 / np.sin(duration * np.pi / period)

    assert np.abs(tmod.params["a"].value - expected_a) < 1e-6

    result = tmod.fit()

    # fit() returns the same MinimizerResult it stashes on the instance.
    assert result is tmod.fit_result

    # t0, rp, a, inclination + the three trends vary; period and the limb
    # darkening parameters are fixed.
    assert result.nvarys == 7

    # Check the non-exoplanet trends
    for fit_trend in ["airmass_trend", "width_trend", "spp_trend"]:
        assert (
            np.abs(tmod.params[fit_trend].value - DEFAULT_TESTING_PARAMS[fit_trend])
            < 1e-5
        )

    # Check a few of the exoplanet parameters
    assert np.abs(tmod.params["t0"].value - DEFAULT_TESTING_PARAMS["t0"]) < 1e-3

    assert np.abs(tmod.params["a"].value - expected_a) < 1e-2

    expected_rp = np.sqrt(DEFAULT_TESTING_PARAMS["depth"] / 1000)
    assert np.abs(tmod.params["rp"].value - expected_rp) < 1e-4

    assert "airmass" in tmod._detrend_parameters
    assert "width" in tmod._detrend_parameters
    assert "spp" in tmod._detrend_parameters

    # Every varying parameter should have a real uncertainty after the fit.
    varying = [
        "t0",
        "rp",
        "a",
        "inclination",
        "airmass_trend",
        "width_trend",
        "spp_trend",
    ]
    for name in varying:
        assert tmod.params[name].vary
        assert tmod.params[name].stderr is not None


def test_transit_fit_parameters_unfreeze_as_expected():
    # The user explicitly asks to fit all three trends, even though none of
    # the covariates (airmass/width/spp) are actually set on the model.
    tmod = _make_transit_model_with_data(
        noise_dev=1e-5, with_airmass=False, with_width=False, with_spp=False
    )

    tmod.params["airmass_trend"].vary = True
    tmod.params["width_trend"].vary = True
    tmod.params["spp_trend"].vary = True

    tmod.fit()

    # fit() runs on a copy of self.params: covariates that are unset get their
    # trend forced to value=0/vary=False *on that copy* so there is nothing to
    # restore. The user's vary=True request on self.params is left untouched.
    assert tmod.params["airmass_trend"].vary
    assert tmod.params["width_trend"].vary
    assert tmod.params["spp_trend"].vary

    # And since there was no covariate data to fit them against, the trend
    # values remain at their unfit default.
    assert tmod.params["airmass_trend"].value == 0
    assert tmod.params["width_trend"].value == 0
    assert tmod.params["spp_trend"].value == 0


def test_transit_model_detrend():
    tmod = _make_transit_model_with_data(
        noise_dev=0, with_airmass=True, with_width=True, with_spp=True
    )

    no_trends = _make_transit_model_with_data(
        noise_dev=0, with_airmass=False, with_width=False, with_spp=False
    )
    full_model = tmod.model_light_curve()

    np.testing.assert_allclose(
        full_model - no_trends.model_light_curve(),
        tmod.params["airmass_trend"].value * tmod.airmass
        + tmod.params["width_trend"].value * tmod.width
        + tmod.params["spp_trend"].value * tmod.spp,
    )

    for trend in tmod._all_detrend_params:
        detrended_model = tmod.model_light_curve(detrend_by=trend)
        trend_param = tmod.params[f"{trend}_trend"].value
        trend_data = getattr(tmod, trend)
        assert trend_param != 0
        assert trend_data is not None
        np.testing.assert_allclose(
            full_model - detrended_model, trend_param * trend_data
        )

    detrended_model = tmod.model_light_curve(detrend_by="all")
    np.testing.assert_allclose(detrended_model, no_trends.model_light_curve())


def test_transit_data_detrend():
    tmod = _make_transit_model_with_data(
        noise_dev=0, with_airmass=True, with_width=True, with_spp=True
    )

    no_trends = _make_transit_model_with_data(
        noise_dev=0, with_airmass=False, with_width=False, with_spp=False
    )

    np.testing.assert_allclose(tmod.data_light_curve(detrend_by="all"), no_trends.data)
    np.testing.assert_allclose(
        tmod.data - no_trends.data,
        tmod.params["airmass_trend"].value * tmod.airmass
        + tmod.params["width_trend"].value * tmod.width
        + tmod.params["spp_trend"].value * tmod.spp,
    )


def test_setup_model_duration_period_guards():
    # duration >= period is unphysical (a transit as long as the orbit itself);
    # guard against it with a clear error instead of a bizarre arcsine-domain
    # failure or a silently nonsensical "a" estimate.
    tmod = TransitModelFit()
    with pytest.raises(ValueError, match="duration"):
        tmod.setup_model(duration=5, period=5)

    tmod_gt = TransitModelFit()
    with pytest.raises(ValueError, match="duration"):
        tmod_gt.setup_model(duration=6, period=5)

    # duration=0 (the default) means "don't seed a": it stays at its default
    # value instead of being estimated from a degenerate duration.
    tmod_no_duration = TransitModelFit()
    tmod_no_duration.setup_model(duration=0, period=5)
    assert tmod_no_duration.params["a"].value == 10.0

    # depth=0 (the default) means "don't seed rp": it stays at its default
    # value. (TRF would otherwise raise "x0 is infeasible" for rp=0, which is
    # below its 0.01 lower bound.)
    tmod_no_depth = TransitModelFit()
    tmod_no_depth.setup_model(depth=0)
    assert tmod_no_depth.params["rp"].value == 0.1


def test_setup_model_applies_model_options():
    from stellarphot.transit_fitting import TransitModelOptions

    options = TransitModelOptions(
        keep_transit_time_fixed=False,
        transit_time_range=60.0,
        keep_radius_planet_fixed=True,
        keep_radius_orbit_fixed=True,
        fit_airmass=True,
        fit_width=False,
        fit_spp=True,
    )

    tmod = TransitModelFit()
    tmod.setup_model(t0=2.0, period=5, model_options=options)

    half_range_days = 60.0 / (24 * 60) / 2
    assert tmod.params["t0"].vary is True
    assert tmod.params["t0"].min == pytest.approx(2.0 - half_range_days)
    assert tmod.params["t0"].max == pytest.approx(2.0 + half_range_days)

    assert tmod.params["rp"].vary is False
    assert tmod.params["a"].vary is False

    assert tmod.params["airmass_trend"].vary is True
    assert tmod.params["width_trend"].vary is False
    assert tmod.params["spp_trend"].vary is True


def test_fit_succeeds_with_inclination_seed_on_bound():
    # The default setup seeds inclination at 90, which is also its upper
    # bound. A fit must still succeed -- this locks in method="least_squares"
    # (TRF), since MINPACK's leastsq can fail/hang when a parameter starts
    # exactly on its bound.
    tmod = _make_transit_model_with_data(
        noise_dev=1e-6, with_airmass=False, with_width=False, with_spp=False
    )

    result = tmod.fit()

    assert result.success is True


def test_fit_result_bic():
    tmod = _make_transit_model_with_data(
        noise_dev=1e-5, with_airmass=False, with_width=False, with_spp=False
    )

    result = tmod.fit()

    assert np.isfinite(tmod.fit_result.bic)
    assert tmod.fit_result.bic == result.bic


def _make_model_with_only_airmass_trend(noise_dev=1e-5):
    # A model where the data contain a strong airmass trend but no width or
    # spp trend, with all three covariates available so compare_detrend_options
    # actually has a choice to make among them.
    tmod = TransitModelFit()

    params = dict(DEFAULT_TESTING_PARAMS)
    params["airmass_trend"] = 0.05
    params["width_trend"] = 0.0
    params["spp_trend"] = 0.0
    tmod.setup_model(**params)

    t0 = DEFAULT_TESTING_PARAMS["t0"]
    duration = DEFAULT_TESTING_PARAMS["duration"]
    start = t0 - duration / 2 * 1.3
    end = t0 + duration / 2 * 1.3
    times = np.linspace(start, end, num=100)
    tmod.times = times

    airmass = 0.4 / (times[0] - times[-1]) ** 2 * (times - times[-1]) ** 2 + 1.0
    width = 4 * (times - times[0]) / (times[-1] - times[0]) + 5
    spp = 30 + 5 * np.sin(4 * np.pi * times / (times[-1] - times[0]))

    tmod.airmass = airmass
    tmod.width = width
    tmod.spp = spp

    # The default noise seed happens to produce a spurious ~2-sigma
    # correlation between the noise and the width covariate, putting the
    # width-included combination within 0.02 BIC of the right answer. This
    # seed has no such accident, so airmass-only wins with a clear margin.
    data = _create_data_from_model_with_trends(tmod, noise_dev=noise_dev, seed=3)
    tmod.data = data

    return tmod


def test_compare_detrend_options_non_destructive():
    tmod = _make_transit_model_with_data(
        noise_dev=1e-5, with_airmass=True, with_width=True, with_spp=True
    )
    tmod.fit()

    fit_result_before = tmod.fit_result
    snapshot_before = {
        name: (p.value, p.vary, p.min, p.max) for name, p in tmod.params.items()
    }

    table1 = tmod.compare_detrend_options()
    table2 = tmod.compare_detrend_options()

    assert table1.colnames == table2.colnames
    np.testing.assert_allclose(table1["BIC"], table2["BIC"])
    for col in table1.colnames:
        if col == "BIC":
            continue
        np.testing.assert_array_equal(table1[col], table2[col])

    snapshot_after = {
        name: (p.value, p.vary, p.min, p.max) for name, p in tmod.params.items()
    }
    assert snapshot_before == snapshot_after

    # Running the comparison must not disturb the previously-stored fit.
    assert tmod.fit_result is fit_result_before


def test_compare_detrend_options_table_shape():
    tmod = _make_transit_model_with_data(
        noise_dev=1e-5, with_airmass=True, with_width=True, with_spp=True
    )
    tmod.fit()

    table = tmod.compare_detrend_options()

    # 2**3 combinations of the three available trends.
    assert len(table) == 8
    for name in ["airmass", "width", "spp"]:
        assert name in table.colnames
    assert "BIC" in table.colnames

    bic = np.asarray(table["BIC"])
    assert np.all(np.diff(bic) >= 0)


def test_compare_detrend_options_recovers_airmass_trend():
    # With a strong airmass trend and no width/spp trend baked into the data,
    # the lowest-BIC (best, first-row) combination should include airmass but
    # not width or spp, even though all three are available to try.
    tmod = _make_model_with_only_airmass_trend()

    table = tmod.compare_detrend_options()

    best = table[0]
    assert bool(best["airmass"]) is True
    assert bool(best["width"]) is False
    assert bool(best["spp"]) is False


def test_compare_detrend_options_apply_best():
    tmod = _make_model_with_only_airmass_trend()

    table = tmod.compare_detrend_options(apply_best=True)

    assert tmod.params["airmass_trend"].vary is True
    assert tmod.params["width_trend"].vary is False
    assert tmod.params["spp_trend"].vary is False

    best_bic = table["BIC"][0]
    assert tmod.fit_result.bic == pytest.approx(best_bic)


def test_compare_detrend_options_no_covariates():
    tmod = _make_transit_model_with_data(
        noise_dev=1e-5, with_airmass=False, with_width=False, with_spp=False
    )

    table = tmod.compare_detrend_options()

    assert len(table) == 1


def test_failed_fit_leaves_state_untouched(monkeypatch):
    # A raising fit must not corrupt the instance: fit() runs on a copy of
    # self.params (via _run_fit), so a failure part-way through leaves
    # self.params and self.fit_result exactly as they were before the call.
    tmod = _make_transit_model_with_data(
        noise_dev=1e-5, with_airmass=False, with_width=False, with_spp=False
    )

    def _boom(*args, **kwargs):  # noqa: ARG001
        raise RuntimeError("boom")

    monkeypatch.setattr(tmod, "_run_fit", _boom)

    fit_result_before = getattr(tmod, "fit_result", None)
    params_before = {
        name: (p.value, p.vary, p.min, p.max) for name, p in tmod.params.items()
    }

    with pytest.raises(RuntimeError):
        tmod.fit()

    params_after = {
        name: (p.value, p.vary, p.min, p.max) for name, p in tmod.params.items()
    }
    assert params_before == params_after
    assert getattr(tmod, "fit_result", None) is fit_result_before
