# Licensed under a 3-clause BSD style license - see LICENSE.rst
#
# Astropy documentation build configuration file.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this file.
#
# All configuration values have a default. Some values are defined in
# the global Astropy configuration which is loaded here before anything else.
# See astropy.sphinx.conf for which values are set there.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('..'))
# IMPORTANT: the above commented section was generated by sphinx-quickstart, but
# is *NOT* appropriate for astropy or Astropy affiliated packages. It is left
# commented out with this explanation to make it clear why this should not be
# done. If the sys.path entry above is added, when the astropy.sphinx.conf
# import occurs, it will import the *source* version of astropy instead of the
# version installed (if invoked as "make html" or directly with sphinx), or the
# version in the build directory (if "python setup.py build_sphinx" is used).
# Thus, any C-extensions that are needed to build the documentation will *not*
# be accessible, and the documentation will not build correctly.

import datetime
import re
import sys
import tomllib
from importlib import import_module
from pathlib import Path

from sphinx_astropy.conf.v2 import *  # noqa: E402, F403
from sphinx_astropy.conf.v2 import (  # noqa: E402
    exclude_patterns,
    html_theme_options,
    rst_epilog,
)

# Grab minversion from pyproject.toml
with (Path(__file__).parents[1] / "pyproject.toml").open("rb") as f:
    pyproject = tomllib.load(f)

__minimum_python_version__ = pyproject["project"]["requires-python"].replace(">=", "")

# -- General configuration ----------------------------------------------------

# By default, highlight as Python 3.
highlight_language = "python3"

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.2'

# To perform a Sphinx version check that needs to be more specific than
# major.minor, call `check_sphinx_version("x.y.z")` here.
# check_sphinx_version("1.2.1")

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns.append("_templates")

# This is added to the end of RST files - a good place to put substitutions to
# be used globally.
rst_epilog += """
"""

# extensions += ["sphinxcontrib.autodoc_pydantic"]
extensions += [
    "sphinx_design",
    "sphinx_gallery.gen_gallery",
    "myst_parser",
    "sphinxcontrib.mermaid",
]

# Render ```mermaid fences (in the diagram Markdown pages) as the mermaid
# directive. 'antiscript' keeps the diagrams' click-through href links working
# while stripping any scripts.
myst_fence_as_directive = ["mermaid"]
# 'antiscript' keeps the diagrams' click-through href links working while
# stripping any scripts. startOnLoad stays False -- sphinxcontrib-mermaid runs
# the diagrams itself.
mermaid_init_config = {"startOnLoad": False, "securityLevel": "antiscript"}
# The only Markdown pages are docs/diagrams-*.md, whose links are either
# external (GitHub) or rewritten below to point at the rendered API docs.
# Emit them verbatim rather than trying to resolve them as Sphinx cross
# references (which mangles the rewritten ``.html#anchor`` targets).
myst_all_links_external = True
# -- Project information ------------------------------------------------------

# This does not *have* to match the package name, but typically does
project = pyproject["project"]["name"]
author = ", ".join(v["name"] for v in pyproject["project"]["authors"])
copyright = f"{datetime.datetime.now().year}, {author}"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

import_module(pyproject["project"]["name"])
package = sys.modules[pyproject["project"]["name"]]

# The short X.Y version.
version = package.__version__.split("-", 1)[0]
# The full version, including alpha/beta/rc tags.
release = package.__version__

# Only include dev docs in dev version.
dev = "dev" in release
if not dev:
    exclude_patterns += ["development/*"]

# -- Options for HTML output --------------------------------------------------

# A NOTE ON HTML THEMES
# The global astropy configuration uses a custom theme, 'bootstrap-astropy',
# which is installed along with astropy. A different theme can be used or
# the options for this theme can be modified by overriding some of the
# variables set in the global configuration. The variables set in the
# global configuration are listed below, commented out.


# Add any paths that contain custom themes here, relative to this directory.
# To use a different custom theme, add the directory containing the theme.
# html_theme_path = []

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes. To override the custom theme, set this to the
# name of a builtin theme or the name of a custom theme in html_theme_path.
# html_theme = None

html_theme_options.update(
    {
        "github_url": "https://github.com/feder-observatory/stellarphot",
        "use_edit_page_button": True,
        # https://github.com/pydata/pydata-sphinx-theme/issues/1492
        "navigation_with_keys": False,
    }
)

# A dictionary of values to pass into the template engine's context for all pages.
html_context = {
    "default_mode": "dark",
    "to_be_indexed": ["stable", "latest"],
    "is_development": dev,
    "github_user": "feder-observatory",
    "github_repo": "stellarphot",
    "github_version": "main",
    "doc_path": "docs",
}

html_css_files = ["astropy.css"]

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = '_static/stellarphot-logo.svg'

html_theme_options.update(
    {
        "logo": {
            "alt_text": "stellarphot - Home",
            "text": "stellarphot",
            "image_light": "_static/stellarphot-logo.svg",
            "image_dark": "_static/stellarphot-logo.svg",
        }
    }
)

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "_static/favicon.ico"

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = ''

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = f"{project} v{release}"

# Output file base name for HTML help builder.
htmlhelp_basename = project + "doc"


# -- Options for LaTeX output -------------------------------------------------

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
    ("index", project + ".tex", project + " Documentation", author, "manual")
]


# -- Options for manual page output -------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [("index", project.lower(), project + " Documentation", [author], 1)]

# -- Turn on nitpicky mode for sphinx (to warn about references not found) ----
#
# nitpicky = True
# nitpick_ignore = []
#
# Some warnings are impossible to suppress, and you can list specific references
# that should be ignored in a nitpick-exceptions file which should be inside
# the docs/ directory. The format of the file should be:
#
# <type> <class>
#
# for example:
#
# py:class astropy.io.votable.tree.Element
# py:class astropy.io.votable.tree.SimpleElement
# py:class astropy.io.votable.tree.SimpleElementWithContent
#
# Uncomment the following lines to enable the exceptions:
#
# for line in open('nitpick-exceptions'):
#     if line.strip() == "" or line.startswith("#"):
#         continue
#     dtype, target = line.split(None, 1)
#     target = target.strip()
#     nitpick_ignore.append((dtype, six.u(target)))

# -- Rewrite in-repo source links in the diagram pages -----------------------
#
# The docs/diagrams-*.md pages link to source files/directories with paths that
# are relative to the repo (e.g. ``../stellarphot/core.py``) so they remain
# browsable on GitHub. When Sphinx builds those pages we instead point each
# link at the rendered API documentation, at module-section granularity. The
# Markdown files themselves are left untouched -- the rewrite happens only on
# the in-memory source via the ``source-read`` event.

# Modules that have an automodapi section on the API Reference page (see
# stellarphot/api_reference.rst). A referenced file resolves to its nearest
# documented ancestor module.
_DOCUMENTED_MODULES = {
    "stellarphot",
    "stellarphot.core",
    "stellarphot.catalogs",
    "stellarphot.table_representations",
    "stellarphot.differential_photometry",
    "stellarphot.gui",
    "stellarphot.gui.transit_fitting_gui",
    "stellarphot.io",
    "stellarphot.photometry.photometry",
    "stellarphot.photometry.source_detection",
    "stellarphot.photometry.profiles",
    "stellarphot.plotting",
    "stellarphot.settings",
    "stellarphot.transit_fitting",
    "stellarphot.transit_fitting.io",
    "stellarphot.transit_fitting.plotting",
    "stellarphot.utils",
}
# Diagram pages live at the docs root; the API page is one level down.
_API_PAGE = "stellarphot/api_reference.html"
# Modules documented on a different page than the API Reference. The settings
# package is documented on the settings user-guide page.
_MODULE_PAGES = {
    "stellarphot.settings": "stellarphot/settings.html",
}
_GH_BLOB = "https://github.com/feder-observatory/stellarphot/blob/main/"
_GH_TREE = "https://github.com/feder-observatory/stellarphot/tree/main/"

_DIAGRAM_DOCS = {
    "diagrams-01-package-overview",
    "diagrams-02-entry-points",
    "diagrams-03-user-flows",
    "diagrams-04-call-graphs",
}

# Packages with no automodapi section of their own -- point references at them
# to their primary documented submodule instead.
_MODULE_ALIASES = {
    "stellarphot.photometry": "stellarphot.photometry.photometry",
}


def _github_fallback(path):
    # ``path`` is what follows ``../stellarphot/``.
    base = _GH_TREE if path.endswith("/") else _GH_BLOB
    return base + "stellarphot/" + path


def _resolve_link(path):
    # Notebooks are not importable Python, so they have no API page -- send
    # them to GitHub, which renders .ipynb files natively.
    if path.startswith("notebooks") or path.endswith(".ipynb"):
        return _github_fallback(path)
    # Build a dotted module name from the path and walk up to the nearest
    # documented module.
    stem = path.rstrip("/")
    if stem.endswith(".py"):
        stem = stem[:-3]
    if stem in ("", "__init__"):
        dotted = "stellarphot"
    else:
        dotted = "stellarphot." + stem.replace("/", ".")
    parts = dotted.split(".")
    while parts:
        candidate = ".".join(parts)
        candidate = _MODULE_ALIASES.get(candidate, candidate)
        if candidate in _DOCUMENTED_MODULES:
            page = _MODULE_PAGES.get(candidate, _API_PAGE)
            return f"{page}#module-{candidate}"
        parts.pop()
    # Shouldn't happen, but fall back to GitHub rather than emit a broken link.
    return _github_fallback(path)


def _rewrite_repo_links(app, docname, source):
    if docname not in _DIAGRAM_DOCS:
        return
    source[0] = re.sub(
        r'\.\./stellarphot/([^\s)"]*)',
        lambda m: _resolve_link(m.group(1)),
        source[0],
    )


def setup(app):
    app.connect("source-read", _rewrite_repo_links)
